export {default as TeachersLayout} from './Admin/Teachers/TeachersLayout'
export {default as AddTeacherLayout} from './Admin/Teachers/AddTeacherLayout'
export {default as StudentsLayout} from './Admin/Students/StudentsLayout'
export {default as SubjectsLayout} from './Admin/Subjects/SubjectsLayout'
export {default as ClassesLayout} from './Admin/Classes/ClassesLayout'